# -*- coding: utf-8 -*-
"""AI practical-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHwJfsrPGQc7FxPxU2bOOvtx8q1PmaRJ
"""

map_rooms = {
    "A": ["B", "C"],
    "B": ["D"],
    "C": ["D"],
    "D": ["G"],
    "G": [],
}
print("our map:")
print("        A (start)")
print("       / \\")
print("      B   C")
print("      \\  /")
print("        D")
print("        -")
print("        G (Treasure )")
print()
print("Doors from each room:", map_rooms)

def bfs(start, goal):
  to_do = [start]
  visited = set()
  order = []

  while to_do:
    room = to_do.pop(0)

    if room in visited:
      continue
    visited.add(room)
    order.append(room)
    if room == goal:
      return order
    for nxt in map_rooms[room]:
      if nxt not in visited:
        to_do.append(nxt)

  return order
order = bfs("A", "G")
print("BFS checked the rooms in this order:", order)
print("Number of rooms BFS checked:", len(order))

def dfs(start, goal):
    to_do = [start]
    visited = []
    order = []

    while to_do:
        room = to_do.pop()


        if room not in visited:
            visited.append(room)
            order.append(room)

            if room == goal:
                return order

            for nxt in reversed(map_rooms[room]):
                to_do.append(nxt)

    return order

order = dfs("A", "G")
print("Dfs checked the rooms in this order:", order)
print("number of rooms Dfs checked:", len(order))

map_rooms = {
    "A": ["B", "C"],
    "B": ["D"],
    "C": ["D"],
    "D": ["G"],
    "G": [],
}

def dfs(start, goal):
  to_do = [start]
  visited = []
  order = []

  while to_do:
    room = to_do.pop()

    if room in visited:
      continue
    visited.append(room)
    order.append(room)

    if room == goal:
      return order

    for nxt in map_rooms[room]:
        to_do.append(nxt)

  return order

order = dfs("A", "G")
print("DFS checked the rooms in this order:", order)
print("Number of rooms DFS checked:", len(order))

door_cost = {
    ("A","B"): 1,
    ("A","C"): 5,
    ("B","D"): 1,
    ("C","D"): 1,
    ("D","G"): 1,
}
def path_cost(path):
  total = 0
  for i in range(len(path)-1):
    door = (path[i], path[i+1]) # Corrected to use tuples and next element in path
    total = total + door_cost[door] # Corrected to add cost
  return total

path1 = ["A", "B", "D", "G"]
path2 = ["A", "C", "D", "G"]
print("Path 1 A -> B -> D -> G cost:", path_cost(path1))
print("Path 2 A -> C -> D -> G cost:", path_cost(path2))
cost1 = path_cost(path1)
cost2 = path_cost(path2)

if cost1<cost2:
  best_path = path1
  best_cost = cost1
else:
  best_path = path2
  best_cost = cost2

print("path1 cost:", cost1)
print("path2 cost:", cost2)
print()
print("the cheapest path is:", best_path, "with cost", best_cost, "💰")
door_cost[("A", "B")] = 4
door_cost[("A", "C")] = 1

cost1 = path_cost(["A", "B", "D", "G"])
cost2 = path_cost(["A", "C", "D", "G"])

print("New path1 (through B) cost:", cost1)
print("New path2 (through C) cost:", cost2)

bfs_order = bfs("A", "G")
dfs_order = dfs("A", "G")

print("BFS (Breadth First) checked:", len(bfs_order), "rooms ->", bfs_order)
print("DFS (Deep First) checked:", len(dfs_order), "rooms ->", dfs_order)


print("cheapest path:", best_path, "with cost", best_cost)

print("-" * 40)
print()

print("What we learned:")

print("* BFS checks the nearest rooms first (spreads out)")
print("* DFS dives deep down one path first")